<?
$PERM["video"]["*"]="R";
$PERM["online"]["*"]="R";
$PERM["desktop_app"]["*"]="R";
$PERM["pub"]["13"]="T_8";
$PERM["upload"]["13"]="T_8";
$PERM["admin"]["*"]="D";
$PERM["admin"]["1"]="X";
$PERM["admin"]["10"]="X";
$PERM["forum"]["7"]="W";
$PERM["forum"]["6"]="W";
$PERM["blogs"]["7"]="W";
$PERM["blogs"]["6"]="W";
$PERM["news"]["7"]="W";
$PERM["news"]["6"]="W";
$PERM["index.php"]["7"]="W";
$PERM["index.php"]["6"]="W";
$PERM["/"]["*"]="R";
?>